unit RadIA.Core.SkillPortability;

interface

type
  TRadIACanonicalSkill = record
  private
    FExtensionId: string;
    FName: string;
    FDescription: string;
    FInstructions: string;
  public
    constructor Create(
      const AExtensionId: string;
      const AName: string;
      const ADescription: string;
      const AInstructions: string
    );
    property ExtensionId: string read FExtensionId;
    property Name: string read FName;
    property Description: string read FDescription;
    property Instructions: string read FInstructions;
  end;

  TRadIACliSkillArtifact = record
  private
    FExecutorId: string;
    FRelativeFileName: string;
    FContent: string;
  public
    constructor Create(
      const AExecutorId: string;
      const ARelativeFileName: string;
      const AContent: string
    );
    property ExecutorId: string read FExecutorId;
    property RelativeFileName: string read FRelativeFileName;
    property Content: string read FContent;
  end;

  IRadIACliSkillAdapter = interface
    ['{81A68AE6-81A0-4D34-8EC4-52D9359A02C7}']
    function ExecutorId: string;
    function DisplayName: string;
    function CreateArtifact(
      const ASkill: TRadIACanonicalSkill
    ): TRadIACliSkillArtifact;
  end;

  TRadIACliSkillAdapterRegistry = class
  public
    class function Adapters: TArray<IRadIACliSkillAdapter>; static;
    class function TryGet(
      const AExecutorId: string;
      out AAdapter: IRadIACliSkillAdapter
    ): Boolean; static;
  end;

implementation

uses
  System.Character,
  System.IOUtils,
  System.SysUtils;

type
  TRadIACliSkillAdapter = class(TInterfacedObject, IRadIACliSkillAdapter)
  private
    FDisplayName: string;
    FExecutorId: string;
    FProjectDirectory: string;
    function BuildContent(const ASkill: TRadIACanonicalSkill): string;
    function SkillId(const ASkill: TRadIACanonicalSkill): string;
    function YamlText(const AValue: string): string;
  public
    constructor Create(
      const AExecutorId: string;
      const ADisplayName: string;
      const AProjectDirectory: string
    );
    function ExecutorId: string;
    function DisplayName: string;
    function CreateArtifact(
      const ASkill: TRadIACanonicalSkill
    ): TRadIACliSkillArtifact;
  end;

{ TRadIACanonicalSkill }

constructor TRadIACanonicalSkill.Create(
  const AExtensionId: string;
  const AName: string;
  const ADescription: string;
  const AInstructions: string
);
begin
  FExtensionId := Trim(AExtensionId);
  FName := Trim(AName);
  FDescription := Trim(ADescription);
  FInstructions := Trim(AInstructions);
  if FExtensionId = '' then
    raise EArgumentException.Create('Skill extension ID is required.');
  if FName = '' then
    raise EArgumentException.Create('Skill name is required.');
  if FDescription = '' then
    raise EArgumentException.Create('Skill description is required.');
  if FInstructions = '' then
    raise EArgumentException.Create('Skill instructions are required.');
end;

{ TRadIACliSkillArtifact }

constructor TRadIACliSkillArtifact.Create(
  const AExecutorId: string;
  const ARelativeFileName: string;
  const AContent: string
);
begin
  FExecutorId := AExecutorId;
  FRelativeFileName := ARelativeFileName;
  FContent := AContent;
end;

{ TRadIACliSkillAdapter }

constructor TRadIACliSkillAdapter.Create(
  const AExecutorId: string;
  const ADisplayName: string;
  const AProjectDirectory: string
);
begin
  inherited Create;
  FExecutorId := AExecutorId;
  FDisplayName := ADisplayName;
  FProjectDirectory := AProjectDirectory;
end;

function TRadIACliSkillAdapter.BuildContent(
  const ASkill: TRadIACanonicalSkill
): string;
begin
  Result := '---' + sLineBreak +
    'name: ' + SkillId(ASkill) + sLineBreak +
    'description: ' + YamlText(ASkill.Description) + sLineBreak +
    '---' + sLineBreak + sLineBreak +
    '<!-- Generated by RadIA from extension ' + ASkill.ExtensionId + '. -->' +
    sLineBreak + sLineBreak + ASkill.Instructions.Trim + sLineBreak;
end;

function TRadIACliSkillAdapter.CreateArtifact(
  const ASkill: TRadIACanonicalSkill
): TRadIACliSkillArtifact;
var
  LSkillId: string;
begin
  LSkillId := SkillId(ASkill);
  Result := TRadIACliSkillArtifact.Create(
    FExecutorId,
    TPath.Combine(
      TPath.Combine(FProjectDirectory, LSkillId),
      'SKILL.md'
    ),
    BuildContent(ASkill)
  );
end;

function TRadIACliSkillAdapter.DisplayName: string;
begin
  Result := FDisplayName;
end;

function TRadIACliSkillAdapter.ExecutorId: string;
begin
  Result := FExecutorId;
end;

function TRadIACliSkillAdapter.SkillId(
  const ASkill: TRadIACanonicalSkill
): string;
var
  LCharacter: Char;
  LLastWasSeparator: Boolean;
  LSource: string;
begin
  Result := '';
  LLastWasSeparator := False;
  LSource := ASkill.ExtensionId + '-' + ASkill.Name;
  for LCharacter in LSource.ToLower do
    if LCharacter.IsLetterOrDigit then
    begin
      Result := Result + LCharacter;
      LLastWasSeparator := False;
    end
    else if (Result <> '') and not LLastWasSeparator then
    begin
      Result := Result + '-';
      LLastWasSeparator := True;
    end;
  Result := Result.TrimRight(['-']);
  if Length(Result) > 64 then
    SetLength(Result, 64);
  Result := Result.TrimRight(['-']);
end;

function TRadIACliSkillAdapter.YamlText(const AValue: string): string;
begin
  Result := '"' + AValue.Replace('\', '\\').Replace('"', '\"')
    .Replace(#13#10, ' ').Replace(#10, ' ').Replace(#13, ' ') + '"';
end;

{ TRadIACliSkillAdapterRegistry }

class function TRadIACliSkillAdapterRegistry.Adapters:
  TArray<IRadIACliSkillAdapter>;
begin
  Result := [
    TRadIACliSkillAdapter.Create('codex', 'Codex', '.agents\skills'),
    TRadIACliSkillAdapter.Create('claude', 'Claude Code', '.claude\skills'),
    TRadIACliSkillAdapter.Create('gemini', 'Gemini CLI', '.gemini\skills'),
    TRadIACliSkillAdapter.Create('copilot', 'GitHub Copilot CLI', '.github\skills')
  ];
end;

class function TRadIACliSkillAdapterRegistry.TryGet(
  const AExecutorId: string;
  out AAdapter: IRadIACliSkillAdapter
): Boolean;
var
  LAdapter: IRadIACliSkillAdapter;
begin
  AAdapter := nil;
  for LAdapter in Adapters do
    if SameText(LAdapter.ExecutorId, Trim(AExecutorId)) then
    begin
      AAdapter := LAdapter;
      Exit(True);
    end;
  Result := False;
end;

end.
