program RadIATests;

{$DEFINE TESTS}
{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  DUnitX.Loggers.Console,
  DUnitX.Loggers.XML.NUnit,
  DUnitX.TestFramework,

  // Production Units
  RadIA.Core.Types in '..\Source\Core\RadIA.Core.Types.pas',
  RadIA.Core.Version in '..\Source\Core\RadIA.Core.Version.pas',
  RadIA.Core.Tools in '..\Source\Core\RadIA.Core.Tools.pas',
  RadIA.Core.AgentRuntime in '..\Source\Core\RadIA.Core.AgentRuntime.pas',
  RadIA.Core.AgentDiagnostic in '..\Source\Core\RadIA.Core.AgentDiagnostic.pas',
  RadIA.Core.AgentExecutors in '..\Source\Core\RadIA.Core.AgentExecutors.pas',
  RadIA.Core.CliProcess in '..\Source\Core\RadIA.Core.CliProcess.pas',
  RadIA.Core.PseudoTerminal in '..\Source\Core\RadIA.Core.PseudoTerminal.pas',
  RadIA.Core.Terminal in '..\Source\Core\RadIA.Core.Terminal.pas',
  RadIA.Core.TerminalScreen in '..\Source\Core\RadIA.Core.TerminalScreen.pas',
  RadIA.UI.TerminalFrame in '..\Source\UI\RadIA.UI.TerminalFrame.pas',
  RadIA.Core.Onboarding in '..\Source\Core\RadIA.Core.Onboarding.pas',
  RadIA.UI.OnboardingForm in '..\Source\UI\RadIA.UI.OnboardingForm.pas',
  RadIA.UI.Resources in '..\Source\UI\RadIA.UI.Resources.pas',
  RadIA.Tests.OnboardingForm in 'Source\RadIA.Tests.OnboardingForm.pas',
  RadIA.Core.AgentProvider in '..\Source\Core\RadIA.Core.AgentProvider.pas',
  RadIA.Core.AgentController in '..\Source\Core\RadIA.Core.AgentController.pas',
  RadIA.Core.AgentPricing in '..\Source\Core\RadIA.Core.AgentPricing.pas',
  RadIA.Core.CliManager in '..\Source\Core\RadIA.Core.CliManager.pas',
  RadIA.Core.CliMcpSettings in '..\Source\Core\RadIA.Core.CliMcpSettings.pas',
  RadIA.Core.McpProvisioning in '..\Source\Core\RadIA.Core.McpProvisioning.pas',
  RadIA.Core.McpHandshake in '..\Source\Core\RadIA.Core.McpHandshake.pas',
  RadIA.Core.ToolRegistry in '..\Source\Core\RadIA.Core.ToolRegistry.pas',
  RadIA.Core.ToolViews in '..\Source\Core\RadIA.Core.ToolViews.pas',
  RadIA.Core.Extensions in '..\Source\Core\RadIA.Core.Extensions.pas',
  RadIA.Core.DeclarativeExtensions in '..\Source\Core\RadIA.Core.DeclarativeExtensions.pas',
  RadIA.Core.DeclarativeTools in '..\Source\Core\RadIA.Core.DeclarativeTools.pas',
  RadIA.Core.DeclarativeExtensionPackages in '..\Source\Core\RadIA.Core.DeclarativeExtensionPackages.pas',
  RadIA.Core.RsaSignature in '..\Source\Core\RadIA.Core.RsaSignature.pas',
  RadIA.Core.ExtensionPublisherTrust in '..\Source\Core\RadIA.Core.ExtensionPublisherTrust.pas',
  RadIA.Core.ExtensionCatalog in '..\Source\Core\RadIA.Core.ExtensionCatalog.pas',
  RadIA.Core.ExtensionStudio in '..\Source\Core\RadIA.Core.ExtensionStudio.pas',
  RadIA.Core.ExtensionSigning in '..\Source\Core\RadIA.Core.ExtensionSigning.pas',
  RadIA.UI.ExtensionCatalogForm in '..\Source\UI\RadIA.UI.ExtensionCatalogForm.pas',
  RadIA.Core.ToolSecurity in '..\Source\Core\RadIA.Core.ToolSecurity.pas',
  RadIA.Core.Patches in '..\Source\Core\RadIA.Core.Patches.pas',
  RadIA.Core.PatchTools in '..\Source\Core\RadIA.Core.PatchTools.pas',
  RadIA.Core.MultiFilePatches in '..\Source\Core\RadIA.Core.MultiFilePatches.pas',
  RadIA.Core.MultiFilePatchTools in '..\Source\Core\RadIA.Core.MultiFilePatchTools.pas',
  RadIA.Core.DevelopmentTransactions in '..\Source\Core\RadIA.Core.DevelopmentTransactions.pas',
  RadIA.Core.DevelopmentTransactionTools in '..\Source\Core\RadIA.Core.DevelopmentTransactionTools.pas',
  RadIA.Core.Build in '..\Source\Core\RadIA.Core.Build.pas',
  RadIA.Core.BuildTools in '..\Source\Core\RadIA.Core.BuildTools.pas',
  RadIA.Core.DUnitX in '..\Source\Core\RadIA.Core.DUnitX.pas',
  RadIA.Core.DUnitXTools in '..\Source\Core\RadIA.Core.DUnitXTools.pas',
  RadIA.Core.Coverage in '..\Source\Core\RadIA.Core.Coverage.pas',
  RadIA.Core.CoverageTools in '..\Source\Core\RadIA.Core.CoverageTools.pas',
  RadIA.Core.Git in '..\Source\Core\RadIA.Core.Git.pas',
  RadIA.Core.GitTools in '..\Source\Core\RadIA.Core.GitTools.pas',
  RadIA.OTA.Git in '..\Source\Integration\RadIA.OTA.Git.pas',
  RadIA.Core.Mcp in '..\Source\Core\RadIA.Core.Mcp.pas',
  RadIA.Core.Designer in '..\Source\Core\RadIA.Core.Designer.pas',
  RadIA.Core.DesignerTools in '..\Source\Core\RadIA.Core.DesignerTools.pas',
  RadIA.Core.DesignerMutations in '..\Source\Core\RadIA.Core.DesignerMutations.pas',
  RadIA.Core.DesignerMutationTools in '..\Source\Core\RadIA.Core.DesignerMutationTools.pas',
  RadIA.Core.DesignerProperties in '..\Source\Core\RadIA.Core.DesignerProperties.pas',
  RadIA.Core.DesignerPropertyTools in '..\Source\Core\RadIA.Core.DesignerPropertyTools.pas',
  RadIA.Core.DesignerComponents in '..\Source\Core\RadIA.Core.DesignerComponents.pas',
  RadIA.Core.DesignerComponentTools in '..\Source\Core\RadIA.Core.DesignerComponentTools.pas',
  RadIA.Core.DesignerEvents in '..\Source\Core\RadIA.Core.DesignerEvents.pas',
  RadIA.Core.DesignerEventTools in '..\Source\Core\RadIA.Core.DesignerEventTools.pas',
  RadIA.Core.Debugger in '..\Source\Core\RadIA.Core.Debugger.pas',
  RadIA.Core.DebugTimeline in '..\Source\Core\RadIA.Core.DebugTimeline.pas',
  RadIA.Core.DebugTimelineTools in '..\Source\Core\RadIA.Core.DebugTimelineTools.pas',
  RadIA.Core.DebuggerTools in '..\Source\Core\RadIA.Core.DebuggerTools.pas',
  RadIA.Core.DebuggerControlTools in '..\Source\Core\RadIA.Core.DebuggerControlTools.pas',
  RadIA.Core.DebuggerBreakpointTools in '..\Source\Core\RadIA.Core.DebuggerBreakpointTools.pas',
  RadIA.Core.DebuggerWatches in '..\Source\Core\RadIA.Core.DebuggerWatches.pas',
  RadIA.Core.DebuggerInspectionTools in '..\Source\Core\RadIA.Core.DebuggerInspectionTools.pas',
  RadIA.Core.RuntimeAutomation in '..\Source\Core\RadIA.Core.RuntimeAutomation.pas',
  RadIA.Core.RuntimeScenario in '..\Source\Core\RadIA.Core.RuntimeScenario.pas',
  RadIA.Core.RuntimeScenarioTools in '..\Source\Core\RadIA.Core.RuntimeScenarioTools.pas',
  RadIA.Core.RuntimeDebugSession in '..\Source\Core\RadIA.Core.RuntimeDebugSession.pas',
  RadIA.Core.RuntimeDebugTools in '..\Source\Core\RadIA.Core.RuntimeDebugTools.pas',
  RadIA.Core.RuntimeDiscoveryTools in '..\Source\Core\RadIA.Core.RuntimeDiscoveryTools.pas',
  RadIA.Core.InlineReviews in '..\Source\Core\RadIA.Core.InlineReviews.pas',
  RadIA.Core.InlineCompletion in '..\Source\Core\RadIA.Core.InlineCompletion.pas',
  RadIA.Core.InlineShortcuts in '..\Source\Core\RadIA.Core.InlineShortcuts.pas',
  RadIA.Core.InlineReviewTools in '..\Source\Core\RadIA.Core.InlineReviewTools.pas',
  RadIA.Core.IDENavigation in '..\Source\Core\RadIA.Core.IDENavigation.pas',
  RadIA.Core.IDENavigationTools in '..\Source\Core\RadIA.Core.IDENavigationTools.pas',
  RadIA.Core.Knowledge in '..\Source\Core\RadIA.Core.Knowledge.pas',
  RadIA.Core.KnowledgeEmbeddings in '..\Source\Core\RadIA.Core.KnowledgeEmbeddings.pas',
  RadIA.Core.RemoteKnowledgeEmbeddings in '..\Source\Core\RadIA.Core.RemoteKnowledgeEmbeddings.pas',
  RadIA.Core.KnowledgeEmbeddingSelection in '..\Source\Core\RadIA.Core.KnowledgeEmbeddingSelection.pas',
  RadIA.Core.RemoteKnowledgeSettings in '..\Source\Core\RadIA.Core.RemoteKnowledgeSettings.pas',
  RadIA.Core.KnowledgePrivacy in '..\Source\Core\RadIA.Core.KnowledgePrivacy.pas',
  RadIA.Core.KnowledgeHistory in '..\Source\Core\RadIA.Core.KnowledgeHistory.pas',
  RadIA.Core.ProjectHealthTools in '..\Source\Core\RadIA.Core.ProjectHealthTools.pas',
  RadIA.Core.InstallationHealthTools in '..\Source\Core\RadIA.Core.InstallationHealthTools.pas',
  RadIA.Core.Journeys in '..\Source\Core\RadIA.Core.Journeys.pas',
  RadIA.Core.KnowledgeTools in '..\Source\Core\RadIA.Core.KnowledgeTools.pas',
  RadIA.Core.KnowledgeStore in '..\Source\Core\RadIA.Core.KnowledgeStore.pas',
  RadIA.Core.KnowledgeScheduler in '..\Source\Core\RadIA.Core.KnowledgeScheduler.pas',
  RadIA.Core.Workspace in '..\Source\Core\RadIA.Core.Workspace.pas',
  RadIA.Core.WorkspaceBoundary in '..\Source\Core\RadIA.Core.WorkspaceBoundary.pas',
  RadIA.Core.WorkspaceTools in '..\Source\Core\RadIA.Core.WorkspaceTools.pas',
  RadIA.Core.Interfaces in '..\Source\Core\RadIA.Core.Interfaces.pas',
  RadIA.Core.ChatMessage in '..\Source\Core\RadIA.Core.ChatMessage.pas',
  RadIA.Core.Container in '..\Source\Core\RadIA.Core.Container.pas',
  RadIA.Core.Logger in '..\Source\Core\RadIA.Core.Logger.pas',
  RadIA.Core.ConfigDefaults in '..\Source\Core\RadIA.Core.ConfigDefaults.pas',
  RadIA.Core.CredentialProtector in '..\Source\Core\RadIA.Core.CredentialProtector.pas',
  RadIA.Core.Config in '..\Source\Core\RadIA.Core.Config.pas',
  RadIA.Core.SettingsStorage in '..\Source\Core\RadIA.Core.SettingsStorage.pas',
  RadIA.Core.ProviderRegistry in '..\Source\Core\RadIA.Core.ProviderRegistry.pas',
  RadIA.Core.Cache in '..\Source\Core\RadIA.Core.Cache.pas',
  RadIA.Core.Service in '..\Source\Core\RadIA.Core.Service.pas',
  RadIA.Core.PromptHistory in '..\Source\Core\RadIA.Core.PromptHistory.pas',
  RadIA.Core.TokenUsage in '..\Source\Core\RadIA.Core.TokenUsage.pas',
  RadIA.Core.ConversationExporter in '..\Source\Core\RadIA.Core.ConversationExporter.pas',
  RadIA.Core.PromptTemplates in '..\Source\Core\RadIA.Core.PromptTemplates.pas',
  RadIA.Core.ProjectContext in '..\Source\Core\RadIA.Core.ProjectContext.pas',
  RadIA.Core.Sessions in '..\Source\Core\RadIA.Core.Sessions.pas',
  RadIA.Core.DTO.Generator in '..\Source\Core\RadIA.Core.DTO.Generator.pas',
  RadIA.Core.ProjectGenerator in '..\Source\Core\RadIA.Core.ProjectGenerator.pas',
  RadIA.Core.ProjectFiles in '..\Source\Core\RadIA.Core.ProjectFiles.pas',
  RadIA.Core.ProjectFileTools in '..\Source\Core\RadIA.Core.ProjectFileTools.pas',
  RadIA.Core.ProjectOpening in '..\Source\Core\RadIA.Core.ProjectOpening.pas',
  RadIA.Core.ProjectTemplates in '..\Source\Core\RadIA.Core.ProjectTemplates.pas',
  RadIA.Core.ProjectTransaction in '..\Source\Core\RadIA.Core.ProjectTransaction.pas',
  RadIA.Core.ProjectTemplateService in '..\Source\Core\RadIA.Core.ProjectTemplateService.pas',
  RadIA.Core.ProjectTemplateTools in '..\Source\Core\RadIA.Core.ProjectTemplateTools.pas',
  RadIA.Core.HttpClient in '..\Source\Core\RadIA.Core.HttpClient.pas',
  RadIA.Core.ErrorDecoder in '..\Source\Core\RadIA.Core.ErrorDecoder.pas',
  RadIA.Core.Localizer in '..\Source\Core\RadIA.Core.Localizer.pas',
  RadIA.OTA.Adapter in '..\Source\Integration\RadIA.OTA.Adapter.pas',
  RadIA.OTA.Workspace in '..\Source\Integration\RadIA.OTA.Workspace.pas',
  RadIA.OTA.Designer in '..\Source\Integration\RadIA.OTA.Designer.pas',
  RadIA.OTA.Debugger in '..\Source\Integration\RadIA.OTA.Debugger.pas',
  RadIA.OTA.RuntimeProcess in '..\Source\Integration\RadIA.OTA.RuntimeProcess.pas',
  RadIA.OTA.RuntimeDiscovery in '..\Source\Integration\RadIA.OTA.RuntimeDiscovery.pas',
  RadIA.OTA.TextReader in '..\Source\Integration\RadIA.OTA.TextReader.pas',
  RadIA.OTA.Knowledge in '..\Source\Integration\RadIA.OTA.Knowledge.pas',
  RadIA.OTA.KnowledgeNotifier in '..\Source\Integration\RadIA.OTA.KnowledgeNotifier.pas',
  RadIA.OTA.InlineReviews in '..\Source\Integration\RadIA.OTA.InlineReviews.pas',
  RadIA.OTA.InlineCompletion in '..\Source\Integration\RadIA.OTA.InlineCompletion.pas',
  RadIA.OTA.IDENavigation in '..\Source\Integration\RadIA.OTA.IDENavigation.pas',
  RadIA.OTA.Consent in '..\Source\Integration\RadIA.OTA.Consent.pas',
  RadIA.OTA.Build in '..\Source\Integration\RadIA.OTA.Build.pas',
  RadIA.MCP.NamedPipe in '..\Source\Integration\RadIA.MCP.NamedPipe.pas',
  RadIA.OTA.Helper in '..\Source\Integration\RadIA.OTA.Helper.pas',
  RadIA.OTA.EditorHook in '..\Source\Integration\RadIA.OTA.EditorHook.pas',
  RadIA.OTA.ContextParser in '..\Source\Integration\RadIA.OTA.ContextParser.pas',
  RadIA.OTA.MessageViewHook in '..\Source\Integration\RadIA.OTA.MessageViewHook.pas',
  RadIA.Core.Mediator in '..\Source\Core\RadIA.Core.Mediator.pas',
  RadIA.Core.OAuth in '..\Source\Core\RadIA.Core.OAuth.pas',
  RadIA.Core.IndyLoopback in '..\Source\Core\RadIA.Core.IndyLoopback.pas',
  RadIA.Provider.Streaming in '..\Source\Providers\RadIA.Provider.Streaming.pas',
  RadIA.Provider.Base in '..\Source\Providers\RadIA.Provider.Base.pas',
  RadIA.Provider.Gemini in '..\Source\Providers\RadIA.Provider.Gemini.pas',
  RadIA.Provider.OpenAI in '..\Source\Providers\RadIA.Provider.OpenAI.pas',
  RadIA.Provider.Claude in '..\Source\Providers\RadIA.Provider.Claude.pas',
  RadIA.Provider.Ollama in '..\Source\Providers\RadIA.Provider.Ollama.pas',
  RadIA.Provider.DeepSeek in '..\Source\Providers\RadIA.Provider.DeepSeek.pas',
  RadIA.Provider.Groq in '..\Source\Providers\RadIA.Provider.Groq.pas',
  RadIA.Provider.OpenRouter in '..\Source\Providers\RadIA.Provider.OpenRouter.pas',
  RadIA.Provider.Generic in '..\Source\Providers\RadIA.Provider.Generic.pas',
  RadIA.Provider.LMStudio in '..\Source\Providers\RadIA.Provider.LMStudio.pas',
  RadIA.Provider.AzureOpenAI in '..\Source\Providers\RadIA.Provider.AzureOpenAI.pas',
  RadIA.Provider.Qwen in '..\Source\Providers\RadIA.Provider.Qwen.pas',
  RadIA.Provider.Mistral in '..\Source\Providers\RadIA.Provider.Mistral.pas',
  RadIA.Core.AwsSigner in '..\Source\Core\RadIA.Core.AwsSigner.pas',
  RadIA.Core.TextNormalizer in '..\Source\Core\RadIA.Core.TextNormalizer.pas',
  RadIA.Provider.GithubCopilot in '..\Source\Providers\RadIA.Provider.GithubCopilot.pas',
  RadIA.Provider.Bedrock in '..\Source\Providers\RadIA.Provider.Bedrock.pas',
  RadIA.UI.ChatPresenter in '..\Source\UI\RadIA.UI.ChatPresenter.pas',
  RadIA.UI.ConfigPresenter in '..\Source\UI\RadIA.UI.ConfigPresenter.pas',

  // Test Suites
  RadIA.Tests.Config in 'Source\RadIA.Tests.Config.pas',
  RadIA.Tests.EditorHook in 'Source\RadIA.Tests.EditorHook.pas',
  RadIA.Tests.ContextParser in 'Source\RadIA.Tests.ContextParser.pas',
  RadIA.Tests.Providers in 'Source\RadIA.Tests.Providers.pas',
  RadIA.Tests.Cache in 'Source\RadIA.Tests.Cache.pas',
  RadIA.Tests.Ollama in 'Source\RadIA.Tests.Ollama.pas',
  RadIA.Tests.Service in 'Source\RadIA.Tests.Service.pas',
  RadIA.Tests.PromptHistory in 'Source\RadIA.Tests.PromptHistory.pas',
  RadIA.Tests.TokenUsage in 'Source\RadIA.Tests.TokenUsage.pas',
  RadIA.Tests.Exporter in 'Source\RadIA.Tests.Exporter.pas',
  RadIA.Tests.Templates in 'Source\RadIA.Tests.Templates.pas',
  RadIA.Tests.ProjectContext in 'Source\RadIA.Tests.ProjectContext.pas',
  RadIA.Tests.Streaming in 'Source\RadIA.Tests.Streaming.pas',
  RadIA.Tests.ProvidersEx in 'Source\RadIA.Tests.ProvidersEx.pas',
  RadIA.Tests.Logger in 'Source\RadIA.Tests.Logger.pas',
  RadIA.Tests.Sessions in 'Source\RadIA.Tests.Sessions.pas',
  RadIA.Tests.Quota in 'Source\RadIA.Tests.Quota.pas',
  RadIA.Tests.DTOGenerator in 'Source\RadIA.Tests.DTOGenerator.pas',
  RadIA.Tests.JSONProviders in 'Source\RadIA.Tests.JSONProviders.pas',
  RadIA.Tests.Analysis in 'Source\RadIA.Tests.Analysis.pas',
  RadIA.Tests.ChatPresenter in 'Source\RadIA.Tests.ChatPresenter.pas',
  RadIA.Tests.ConfigPresenter in 'Source\RadIA.Tests.ConfigPresenter.pas',
  RadIA.Tests.ProjectGenerator in 'Source\RadIA.Tests.ProjectGenerator.pas',
  RadIA.Tests.ProjectFiles in 'Source\RadIA.Tests.ProjectFiles.pas',
  RadIA.Tests.ProjectTemplates in 'Source\RadIA.Tests.ProjectTemplates.pas',
  RadIA.Tests.ProjectTemplateTools in 'Source\RadIA.Tests.ProjectTemplateTools.pas',
  RadIA.Tests.Container in 'Source\RadIA.Tests.Container.pas',
  RadIA.Tests.Infrastructure in 'Source\RadIA.Tests.Infrastructure.pas',
  RadIA.Tests.OAuth in 'Source\RadIA.Tests.OAuth.pas',
  RadIA.Tests.IndyLoopback in 'Source\RadIA.Tests.IndyLoopback.pas',
  RadIA.Tests.TextNormalizer in 'Source\RadIA.Tests.TextNormalizer.pas',
  RadIA.Tests.AwsSigner in 'Source\RadIA.Tests.AwsSigner.pas',
  RadIA.Tests.Mediator in 'Source\RadIA.Tests.Mediator.pas',
  RadIA.Tests.ProviderBooster in 'Source\RadIA.Tests.ProviderBooster.pas',
  RadIA.Tests.CoverageBooster in 'Source\RadIA.Tests.CoverageBooster.pas',
  RadIA.Tests.OTAHelper in 'Source\RadIA.Tests.OTAHelper.pas',
  RadIA.Tests.HttpClient in 'Source\RadIA.Tests.HttpClient.pas',
  RadIA.Tests.ToolRegistry in 'Source\RadIA.Tests.ToolRegistry.pas',
  RadIA.Tests.ToolViews in 'Source\RadIA.Tests.ToolViews.pas',
  RadIA.Tests.AgentRuntime in 'Source\RadIA.Tests.AgentRuntime.pas',
  RadIA.Tests.AgentExecutors in 'Source\RadIA.Tests.AgentExecutors.pas',
  RadIA.Tests.CliProcess in 'Source\RadIA.Tests.CliProcess.pas',
  RadIA.Tests.Terminal in 'Source\RadIA.Tests.Terminal.pas',
  RadIA.Tests.Onboarding in 'Source\RadIA.Tests.Onboarding.pas',
  RadIA.Tests.CliManager in 'Source\RadIA.Tests.CliManager.pas',
  RadIA.Tests.CliMcpSettings in 'Source\RadIA.Tests.CliMcpSettings.pas',
  RadIA.Tests.McpProvisioning in 'Source\RadIA.Tests.McpProvisioning.pas',
  RadIA.Tests.McpHandshake in 'Source\RadIA.Tests.McpHandshake.pas',
  RadIA.Tests.WorkspaceTools in 'Source\RadIA.Tests.WorkspaceTools.pas',
  RadIA.Tests.WorkspaceBoundary in 'Source\RadIA.Tests.WorkspaceBoundary.pas',
  RadIA.Tests.Patches in 'Source\RadIA.Tests.Patches.pas',
  RadIA.Tests.MultiFilePatches in 'Source\RadIA.Tests.MultiFilePatches.pas',
  RadIA.Tests.DevelopmentTransactions in 'Source\RadIA.Tests.DevelopmentTransactions.pas',
  RadIA.Tests.BuildTools in 'Source\RadIA.Tests.BuildTools.pas',
  RadIA.Tests.DUnitX in 'Source\RadIA.Tests.DUnitX.pas',
  RadIA.Tests.Coverage in 'Source\RadIA.Tests.Coverage.pas',
  RadIA.Tests.Git in 'Source\RadIA.Tests.Git.pas',
  RadIA.Tests.Mcp in 'Source\RadIA.Tests.Mcp.pas',
  RadIA.Tests.DesignerTools in 'Source\RadIA.Tests.DesignerTools.pas',
  RadIA.Tests.DesignerMutations in 'Source\RadIA.Tests.DesignerMutations.pas',
  RadIA.Tests.DesignerProperties in 'Source\RadIA.Tests.DesignerProperties.pas',
  RadIA.Tests.DebuggerTools in 'Source\RadIA.Tests.DebuggerTools.pas',
  RadIA.Tests.DebugTimeline in 'Source\RadIA.Tests.DebugTimeline.pas',
  RadIA.Tests.DebuggerControlTools in 'Source\RadIA.Tests.DebuggerControlTools.pas',
  RadIA.Tests.DebuggerBreakpointTools in 'Source\RadIA.Tests.DebuggerBreakpointTools.pas',
  RadIA.Tests.DebuggerInspectionTools in 'Source\RadIA.Tests.DebuggerInspectionTools.pas',
  RadIA.Tests.RuntimeAutomation in 'Source\RadIA.Tests.RuntimeAutomation.pas',
  RadIA.Tests.RuntimeDebugSession in 'Source\RadIA.Tests.RuntimeDebugSession.pas',
  RadIA.Tests.RuntimeDebugTools in 'Source\RadIA.Tests.RuntimeDebugTools.pas',
  RadIA.Tests.RuntimeDiscovery in 'Source\RadIA.Tests.RuntimeDiscovery.pas',
  RadIA.Tests.RuntimeScenario in 'Source\RadIA.Tests.RuntimeScenario.pas',
  RadIA.Tests.InlineReviews in 'Source\RadIA.Tests.InlineReviews.pas',
  RadIA.Tests.InlineCompletion in 'Source\RadIA.Tests.InlineCompletion.pas',
  RadIA.Tests.IDENavigation in 'Source\RadIA.Tests.IDENavigation.pas',
  RadIA.Tests.Knowledge in 'Source\RadIA.Tests.Knowledge.pas',
  RadIA.Tests.RemoteKnowledgeEmbeddings in 'Source\RadIA.Tests.RemoteKnowledgeEmbeddings.pas',
  RadIA.Tests.KnowledgeEmbeddingSelection in 'Source\RadIA.Tests.KnowledgeEmbeddingSelection.pas',
  RadIA.Tests.RemoteKnowledgeSettings in 'Source\RadIA.Tests.RemoteKnowledgeSettings.pas',
  RadIA.Tests.KnowledgePrivacy in 'Source\RadIA.Tests.KnowledgePrivacy.pas',
  RadIA.Tests.ProjectHealthTools in 'Source\RadIA.Tests.ProjectHealthTools.pas',
  RadIA.Tests.InstallationHealthTools in 'Source\RadIA.Tests.InstallationHealthTools.pas',
  RadIA.Tests.Journeys in 'Source\RadIA.Tests.Journeys.pas',
  RadIA.Tests.KnowledgeScheduler in 'Source\RadIA.Tests.KnowledgeScheduler.pas',
  RadIA.Tests.KnowledgeNotifier in 'Source\RadIA.Tests.KnowledgeNotifier.pas',
  RadIA.Tests.Extensions in 'Source\RadIA.Tests.Extensions.pas',
  RadIA.Tests.DeclarativeExtensions in 'Source\RadIA.Tests.DeclarativeExtensions.pas',
  RadIA.Tests.DeclarativeExtensionPackages in 'Source\RadIA.Tests.DeclarativeExtensionPackages.pas',
  RadIA.Tests.ExtensionCatalog in 'Source\RadIA.Tests.ExtensionCatalog.pas',
  RadIA.Tests.ExtensionStudio in 'Source\RadIA.Tests.ExtensionStudio.pas',
  RadIA.Tests.DesignerComponents in 'Source\RadIA.Tests.DesignerComponents.pas',
  RadIA.Tests.DesignerEvents in 'Source\RadIA.Tests.DesignerEvents.pas',
  RadIA.Tests.ToolSecurity in 'Source\RadIA.Tests.ToolSecurity.pas';

var
  Runner: ITestRunner;
  Results: IRunResults;
  Logger: ITestLogger;
  XmlLogger: ITestLogger;
begin
  try
    TRadIAConfig.SetBaseRegistryPath('Software\RadIA\Tests');
    TDUnitX.CheckCommandLine;
    Runner := TDUnitX.CreateRunner;
    Runner.UseRTTI := True;

    Logger := TDUnitXConsoleLogger.Create(True);
    Runner.AddLogger(Logger);

    XmlLogger := TDUnitXXMLNUnitFileLogger.Create(
      TDUnitX.Options.XMLOutputFile
    );
    Runner.AddLogger(XmlLogger);

    Results := Runner.Execute;

    if not Results.AllPassed then
      System.ExitCode := 1
    else
      System.ExitCode := 0;
  except
    on E: Exception do
    begin
      Writeln(E.ClassName, ': ', E.Message);
      System.ExitCode := 1;
    end;
  end;
end.
