unit RadIA.Tests.SkillPortability;

interface

uses
  DUnitX.TestFramework;

type
  [TestFixture]
  TRadIASkillPortabilityTests = class
  public
    [Test]
    procedure ExposesFourSupportedAdapters;
    [Test]
    procedure GeneratesExecutorSpecificProjectPaths;
    [Test]
    procedure GeneratesPortableSkillFrontmatter;
    [Test]
    procedure RejectsIncompleteCanonicalSkill;
  end;

implementation

uses
  System.SysUtils,
  RadIA.Core.SkillPortability;

function CreateTestSkill: TRadIACanonicalSkill;
begin
  Result := TRadIACanonicalSkill.Create(
    'TeamReview',
    'Review Delphi code',
    'Review code and explain when this workflow should be used.',
    '# Review workflow' + sLineBreak + sLineBreak +
    'Inspect the change, run tests, and report evidence.'
  );
end;

procedure TRadIASkillPortabilityTests.ExposesFourSupportedAdapters;
var
  LAdapters: TArray<IRadIACliSkillAdapter>;
begin
  LAdapters := TRadIACliSkillAdapterRegistry.Adapters;
  Assert.AreEqual<Integer>(4, Length(LAdapters));
  Assert.AreEqual('codex', LAdapters[0].ExecutorId);
  Assert.AreEqual('claude', LAdapters[1].ExecutorId);
  Assert.AreEqual('gemini', LAdapters[2].ExecutorId);
  Assert.AreEqual('copilot', LAdapters[3].ExecutorId);
end;

procedure TRadIASkillPortabilityTests.GeneratesExecutorSpecificProjectPaths;
const
  CExpectedPaths: array[0..3] of string = (
    '.agents\skills\teamreview-review-delphi-code\SKILL.md',
    '.claude\skills\teamreview-review-delphi-code\SKILL.md',
    '.gemini\skills\teamreview-review-delphi-code\SKILL.md',
    '.github\skills\teamreview-review-delphi-code\SKILL.md'
  );
var
  LAdapters: TArray<IRadIACliSkillAdapter>;
  LArtifact: TRadIACliSkillArtifact;
  LIndex: Integer;
begin
  LAdapters := TRadIACliSkillAdapterRegistry.Adapters;
  for LIndex := Low(LAdapters) to High(LAdapters) do
  begin
    LArtifact := LAdapters[LIndex].CreateArtifact(CreateTestSkill);
    Assert.AreEqual(CExpectedPaths[LIndex], LArtifact.RelativeFileName);
  end;
end;

procedure TRadIASkillPortabilityTests.GeneratesPortableSkillFrontmatter;
var
  LAdapter: IRadIACliSkillAdapter;
  LArtifact: TRadIACliSkillArtifact;
begin
  Assert.IsTrue(TRadIACliSkillAdapterRegistry.TryGet('CoDeX', LAdapter));
  LArtifact := LAdapter.CreateArtifact(CreateTestSkill);
  Assert.Contains(LArtifact.Content, 'name: teamreview-review-delphi-code');
  Assert.Contains(LArtifact.Content, 'description: "Review code');
  Assert.Contains(LArtifact.Content, 'Generated by RadIA');
  Assert.Contains(LArtifact.Content, '# Review workflow');
end;

procedure TRadIASkillPortabilityTests.RejectsIncompleteCanonicalSkill;
var
  LTestMethod: TTestLocalMethod;
begin
  LTestMethod :=
    procedure
    begin
      TRadIACanonicalSkill.Create('TeamReview', '', 'Description', 'Instructions');
    end;
  Assert.WillRaise(LTestMethod, EArgumentException);
end;

initialization
  TDUnitX.RegisterTestFixture(TRadIASkillPortabilityTests);

end.
